In [11]:
import numpy as np
import math

In [12]:
#numpy dot product
inputss = [1,2,3.5]
weight = [0.2,0.5,-0.1]
bias = 1.2;
outputs = np.dot(weight, inputss)+bias;
print(outputs)

2.05


In [3]:
#4 input neurons with batch size of 3 and 3 output neurons means 3 set of 4 weights and 3 biases for 3 neurons
inp = [[1.2, 0.4, -3.2, 1.4],
    [0.4, 1.1, 1.3, -0.5],
    [0.9, -0.8, -2.3, 1.5]]

w1 = [[0.2, 0.8, -0.5, 1.0],
    [0.5, -0.26, -0.34, 0.44],
    [0.12, -0.3, -0.53, 0.21]]
b1 = [1.2, -2.4, 0.45]
#now we need to take the transpose of the matrix to multiply them
w1 = np.array(w1).T
l1_op = np.dot(inp,w1) + b1
print(l1_op)

[[ 4.76  -0.2    2.464]
 [ 1.01  -3.148 -0.626]
 [ 3.39  -0.3    2.332]]


In [4]:
#adding a second layer to our nn
w2=[
    [1.11, 1.34, 0.98, -1.04],
    [0.32, -0.45, -1.4, -0.23 ],
    [1.23, 0.42, 0.33, 1.76]
]
b2=[-1.34, 0.55, 0.98]
w2 = np.array(w2).T
l2_op = np.dot(inp,w2) + b2
print(l2_op)

[[-4.064  4.912  4.032]
 [ 2.372 -1.522  1.483]
 [-5.227  4.073  3.632]]


In [5]:
def spiral_data(points, classes):
    np.random.seed(0)
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y
X,y = spiral_data(100, 3);
print(y)
#generate data with 2 inout neurons and specified number of classes as output

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2]


In [6]:
class Layer_Dense:
    def __init__(self, n_layers, n_neurons):
        #n_layers in the no of input neurons and n_neurons is the no of output neurons
        np.random.seed(0)
        #initializing the weights for one layer with each row in a column have the weights for each input neuron
        self.weights=0.10*np.random.randn(n_layers, n_neurons)
        #initializing biases columnwise so that they are stacked over each row
        #[1,2,3,5]...
        self.biases=np.zeros((1,n_neurons))
    def forward(self, inputs):
        #running the forward pass to calculate w1x1 + w2x2 + ... + b for each output neuron
        #inputs is actually a matrix with each row containing one time input of size n_layers
        self.output = np.dot(inputs, self.weights) + self.biases
        #size of output will be thus input set size x n_neurons
class Soft_max:
    def forward(self, inputs):
        #take the maximum along axis=1 (along row) and allocates to a new array
        ini = np.max(inputs, axis=1,keepdims=True)
        #subtracting values in each row with their row's maximum so that all numbers are in range of -infinity to 0
        #and thee^num will be in the range of 0 to 1
        inputs = inputs - ini
        #calculates the exponentiation of all the values in then input array
        exp_layer = np.exp(inputs)
        #finding the sum of each row (axis = 1) and thus it creates a single column
        mat= np.sum(exp_layer,axis=1)
        #reshaping mat to column array
        mat = mat.reshape(300,1)
        #then it will automatically broacast 300,1 to 300,3
        self.output = exp_layer/mat
class Activation_ReLU:
    def forward(self, inputs):
        #now the method np.maximum(x1,x2) comapres two arrays (if different shape, then they must be broadcastable)
        #and take the maximum value out of the two and alllocates to a new array
        self.output = np.maximum(0,inputs)    

In [7]:
#applying softmax function to the output
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()
layer1.forward(X)
activation1.forward(layer1.output)
print(activation1.output)
layer2 = Layer_Dense(5,3)
layer2.forward(activation1.output)
activation2 = Soft_max()
activation2.forward(layer2.output)
print(activation2.output[:10])

[[0.         0.         0.         0.         0.        ]
 [0.         0.00103638 0.00014718 0.0005717  0.00095553]
 [0.00075135 0.00199405 0.00102515 0.00272585 0.0030446 ]
 ...
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
[[0.33333333 0.33333333 0.33333333]
 [0.33338343 0.33333969 0.33327688]
 [0.33346423 0.33327849 0.33325728]
 [0.33358644 0.33305793 0.33335563]
 [0.33367097 0.3329884  0.33334062]
 [0.33354979 0.33344213 0.33300809]
 [0.33381839 0.33293762 0.33324399]
 [0.33376832 0.33318648 0.33304519]
 [0.33388376 0.33305874 0.3330575 ]
 [0.33406798 0.33271366 0.33321836]]


In [8]:
#next aim is to calculate the error and minimize it using backpropagation
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output,y)
        data_loss = np.mean(sample_losses)
        return data_loss
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_target):
        samples = len(y_pred)
        y_pred = np.clip(y_pred, 1e-7, 1-1e-7)
        if len(y_target.shape)==1:
            correct_conf = y_pred[range(samples), y_target]
        elif len(y_target.shape==2):
            correct_conf = np.sum(y_pred*y_target, axis = 1)
        y_error = -np.log(correct_conf)
        return y_error
##to implement kaggle wine dataset

In [9]:
Lossfunc = Loss_CategoricalCrossEntropy()
data_loss = Lossfunc.calculate(activation2.output,y)
print(data_loss)

1.0983132858462719


In [10]:
softmax_output = np.array([
    [0.0,0.1,0.2],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]  
])
softmax_output = np.clip(softmax_output, 1e-7 , 1-1e-7)
y_target = [0,1,1]
#extracting iutput for each 
print(-np.log(softmax_output[range(len(softmax_output)), y_target]))

[16.11809565  0.69314718  0.10536052]


In [12]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar